export const stdlibNav = [
  {
    label: "Index",
    slug: "",
    namespaces: []
  },
  {
    label: "IO",
    slug: "io",
    namespaces: [
      {
        label: "File",
        slug: "file",
        methods: [
          { label: "getSize", slug: "getSize" },
          { label: "open", slug: "open" },
          { label: "close", slug: "close" },
          { label: "read", slug: "read" },
        ],
      },
      {
        label: "Log",
        slug: "log",
        methods: [
          { label: "Level", slug: "Level" },
          { label: "trace", slug: "trace" },
          { label: "debug", slug: "debug" },
          { label: "info", slug: "info" },
          { label: "warn", slug: "warn" },
          { label: "error", slug: "error" },
          { label: "msg", slug: "msg" },
        ],
      },
    ],
  },
  {
    label: "Math",
    slug: "math",
    namespaces: [
      {
        label: "Math",
        slug: "math",
        methods: [
          { label: "rad", slug: "rad" },
          { label: "sign", slug: "sign" },
          { label: "fsign", slug: "fsign" },
          { label: "fsignf", slug: "fsignf" },
          { label: "clamp", slug: "clamp" },
          { label: "fclamp", slug: "fclamp" },
          { label: "fclampf", slug: "fclampf" },
        ],
      },
      {
        label: "Matrix",
        slug: "matrix",
        methods: [
          { label: "It", slug: "It" },
          { label: "setIdentity", slug: "setIdentity" },
          { label: "multiply", slug: "multiply" },
          { label: "copy", slug: "copy" },
          { label: "ortho2D", slug: "ortho2D" },
          { label: "ortho2DVk", slug: "ortho2DVk" },
          { label: "projection", slug: "projection" },
          { label: "scale", slug: "scale" },
          { label: "translate", slug: "translate" },
          { label: "rotate", slug: "rotate" },
          { label: "lookAt", slug: "lookAt" },
        ],
      },
      {
        label: "VectorF",
        slug: "vectorf",
        methods: [
          { label: "It", slug: "It" },
          { label: "equals", slug: "equals" },
          { label: "set", slug: "set" },
          { label: "normalize", slug: "normalize" },
          { label: "length", slug: "length" },
          { label: "zero", slug: "zero" },
          { label: "dot", slug: "dot" },
          { label: "cross", slug: "cross" },
          { label: "sub", slug: "sub" },
        ],
      },
      {
        label: "VectorI",
        slug: "vectori",
        methods: [
          { label: "It", slug: "It" },
          { label: "equals", slug: "equals" },
          { label: "set", slug: "set" },
          { label: "normalize", slug: "normalize" },
          { label: "length", slug: "length" },
          { label: "zero", slug: "zero" },
          { label: "dot", slug: "dot" },
          { label: "cross", slug: "cross" },
          { label: "sub", slug: "sub" },
        ],
      },
    ],
  },
  {
    label: "Network",
    slug: "network",
    namespaces: [
      {
        label: "TcpClient",
        slug: "tcpclient",
        methods: [
          { label: "It", slug: "It" },
          { label: "create", slug: "create" },
          { label: "destroy", slug: "destroy" },
          { label: "write", slug: "write" },
          { label: "read", slug: "read" },
          { label: "readAll", slug: "readAll" },
        ],
      },
      {
        label: "TcpServer",
        slug: "tcpserver",
        methods: [
          { label: "It", slug: "It" },
          { label: "create", slug: "create" },
          { label: "destroy", slug: "destroy" },
          { label: "listen", slug: "listen" },
          { label: "write", slug: "write" },
          { label: "read", slug: "read" },
          { label: "readAll", slug: "readAll" },
          { label: "broadcast", slug: "broadcast" },
        ],
      },
    ],
  },
  {
    label: "STD",
    slug: "std",
    namespaces: [
      {
        label: "Buffer",
        slug: "buffer",
        methods: [
          { label: "It", slug: "It" },
          { label: "setOrder", slug: "setOrder" },
          { label: "reset", slug: "reset" },
          { label: "getI8", slug: "getI8" },
          { label: "getU8", slug: "getU8" },
          { label: "getI16", slug: "getI16" },
          { label: "getU16", slug: "getU16" },
          { label: "getI32", slug: "getI32" },
          { label: "getU32", slug: "getU32" },
          { label: "getI64", slug: "getI64" },
          { label: "getU64", slug: "getU64" },
          { label: "getF32", slug: "getF32" },
          { label: "getF64", slug: "getF64" },
          { label: "putI8", slug: "putI8" },
          { label: "putU8", slug: "putU8" },
          { label: "putI16", slug: "putI16" },
          { label: "putU16", slug: "putU16" },
          { label: "putI32", slug: "putI32" },
          { label: "putU32", slug: "putU32" },
          { label: "putI64", slug: "putI64" },
          { label: "putU64", slug: "putU64" },
          { label: "putF32", slug: "putF32" },
          { label: "putF64", slug: "putF64" },
        ],
      },
      {
        label: "DynamicLibrary",
        slug: "dynamiclibrary",
        methods: [
          { label: "It", slug: "It" },
          { label: "load", slug: "load" },
          { label: "get", slug: "get" },
          { label: "unload", slug: "unload" },
        ],
      },
      {
        label: "List",
        slug: "list",
        methods: [
          { label: "It", slug: "It" },
          { label: "add", slug: "add" },
          { label: "addAt", slug: "addAt" },
          { label: "remove", slug: "remove" },
          { label: "removeAt", slug: "removeAt" },
          { label: "get", slug: "get" },
          { label: "set", slug: "set" },
          { label: "first", slug: "first" },
          { label: "last", slug: "last" },
          { label: "size", slug: "size" },
          { label: "clear", slug: "clear" },
        ],
      },
      {
        label: "Mutex",
        slug: "mutex",
        methods: [
          { label: "It", slug: "It" },
          { label: "create", slug: "create" },
          { label: "destroy", slug: "destroy" },
          { label: "lock", slug: "lock" },
          { label: "unlock", slug: "unlock" },
        ],
      },
      {
        label: "Thread",
        slug: "thread",
        methods: [
          { label: "Fn", slug: "Fn" },
          { label: "It", slug: "It" },
          { label: "start", slug: "start" },
          { label: "join", slug: "join" },
        ],
      },
    ],
  }
]
